import { Selector } from 'testcafe';

export default class preview {
    constructor () {
      this.pledge = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > ul > li.tab.active > a > i > span');
      this.pledgeHeadline = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li.tab.active > a > i > span');
      this.pledgeHeadlineText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.pledgeSalutation = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(2)');
      this.pledgeSalutationText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.pledgeBodyMessage = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(3) > a > i > span');
      this.pledgeMicrAndAdv = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > ul > li.tab.active > a > i > span');
      this.pledgeMicrAndAdvText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div.row.content > div > .textcomplete')
      this.pledgeMictAndSub = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > ul > li:nth-child(2)');
      this.pledgeMictAndSubText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div.row.content > div > .textcomplete');
      this.pledgeColor = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(2) > div > ul > li:nth-child(13)');
      this.pledgeFontSize = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(3) > div:nth-child(1) > input');
      this.pledgeTextTransform = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select');
      this.pledgeTextTransformNone = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(1)');
      this.pledgeTextTransformCapitalize = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(2)');
      this.pledgeTextTransformUppercase = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(3)');
      this.pledgeTextTransformLowercase = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(4)');
      this.pledgeFontStyle = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(1) > select');
      this.pledgeFontStyleNormal = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(1)');
      this.pledgeFontStyleItalique = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(2)');    
      this.pledgeFontStyleOblique = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(3)');
      this.pledgeFontWeight = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(2) > select');
      this.pledgeFontWeightNormal = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(1)');
      this.pledgeFontWeightBold = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(2)');
      this.pledgeFontWeightBolder = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(3)');
      this.pledgeFontWeightLighter = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(4)');
      this.pledgeExpandArrow = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-footer > div.collapse-modal > i');
      this.saveBtn = Selector('#save-templates-config');
      this.pledgeCheckHeadline = Selector('.flex-item-10');
      this.pledgeCheckSalutation = Selector('.salutation-block');
      this.pledgeCheckBody = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.flex-row > div > span');
      this.pledgeLinkConnect = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.pledge-bottom.clearfix > div > small > a');
      this.pledgeSendButton = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.pledge-bottom.clearfix > div > div > form > div > div.form-item.form-button.flex-item-2 > button');


    }
}