import { Selector } from 'testcafe';

export default class confirm {
    constructor () {
      this.payConfirm = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > ul > li:nth-child(3) > a > i');
      this.payHeadline = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li.tab.active');
      this.payHeadlineText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.payBodyMessage = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(2) > a > i');
      this.payBodyMessageText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.payFeeling = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(3) > a > i');
      this.payFeelingText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.payFeelingHappy = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(4) > a > i');
      this.payFeelingHappyText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.payFeelingOk = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(5) > a > i');
      this.payFeelingOkText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.payFeelinNotHappy = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(6) > a > i');
      this.payFeelinNotHappyText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.payShareExperience = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(7) > a > i');
      this.payShareExperienceText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.payColor = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(2) > div > ul > li:nth-child(4)');
      this.payText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div:nth-child(1) > input');
      this.payTextTransform = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select');
      this.payTextTransformNone = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(1)');
      this.payTextTransformCapitalise = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(2)');
      this.payTextTransformUppercase = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(3)');
      this.payTextTransformLowercase = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(4)');
      this.payFontStyle = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(1) > select');
      this.payFontStyleNormal = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(1)');
      this.payFontStyleItalique = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(2)');
      this.payFontStyleOblique = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(3)');
      this.payFontWeight = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(2) > select');
      this.payFontWeightNormal = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(1)');
      this.payFontWeightBold = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(2)');
      this.payFontWeightBolder = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(3)');
      this.payFontWeightLighter = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-label-on-focus.vfl-select > select > option:nth-child(4)');
      this.paySmile = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.flex-row.survey-block > div.flex-item-6.mood-block > div > label:nth-child(3) > i');
      this.payMeh = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.flex-row.survey-block > div.flex-item-6.mood-block > div > label:nth-child(5) > i');
      this.paySad = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.flex-row.survey-block > div.flex-item-6.mood-block > div > label:nth-child(7) > i');
    }
}