import { Selector } from 'testcafe';

export default class adview {
    constructor () {
      this.adviewConfirmed = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > ul > li:nth-child(5) > a');
      this.headline = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li.tab.active > a');
      this.headlineText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.shareExperienceBody = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(2) > a');
      this.shareExperienceBodyText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.bodyMessage = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(3) > a');
      this.bodyMessageText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.Feeling = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(4) > a');
      this.FeelingText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.FeelingHappy = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(5) > a');
      this.FeelingHappyText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.FeelingOk = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(6)');
      this.FeelingOkText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.FeelingBad = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(7) > a');
      this.FeelingBadText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.shareExperience = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(8) > a');
      this.shareExperienceText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.color = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(2) > div > ul > li:nth-child(16)');
      this.fontSize = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div:nth-child(1) > input');
      this.textTransform = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select');
      this.textTransformNone = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select > option:nth-child(1)');
      this.textTransformCapitalize = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select > option:nth-child(2)');
      this.textTransformUppercase = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select > option:nth-child(3)');
      this.textTransformLowercase = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select > option:nth-child(4)');
      this.fontStyle = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(1) > select');
      this.fontStyleNormal = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(1)');
      this.fontStyleItalique = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(2)');
      this.fontStyleOblique = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(3)');
      this.fontWeight = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(2) > select');
      this.fontWeightNormal = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(1)');
      this.fontWeightBold = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(2)');
      this.fontWeightBolded = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(3)');
      this.fontWeightLigher = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(4)');
      
    }
}