import { Selector } from 'testcafe';

export default class message {
    constructor () {
      this.messageTab = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > ul > li:nth-child(6) > a');
      this.bodyMessage = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li > a > i');
      this.refundConfirmed = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > ul > li.tab.active');
      this.refundConfirmedText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div.row.content > div > .textcomplete');
      this.unsubscribeConfirmed = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > ul > li:nth-child(2) > a');
      this.unsubscribeConfirmedText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div.row.content > div > .textcomplete');
      this.freeContent = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > ul > li:nth-child(3) > a');
      this.freeContentText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div.row.content > div > .textcomplete');
      this.color = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(2) > div > ul > li:nth-child(28)');
      this.fontSize = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(3) > div:nth-child(1) > input');
      this.textTransform = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select');
      this.textTransformNone = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select > option:nth-child(1)');
      this.textTransformCapitalize = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select > option:nth-child(2)');
      this.textTransformUppercase = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select > option:nth-child(3)');
      this.textTransformLowercase = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select > option:nth-child(4)');
      this.fontStyle = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(1) > select');
      this.fontStyleNormal = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(1)');
      this.fontStyleItalique = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(2)');
      this.fontStyleOblique = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(3)');
      this.fontWeigth = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(2) > select');
      this.fontWeightNormal = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(1)');
      this.fontWeightBold = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(2)');
      this.fontWeightBolder = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(3)');
      this.fontWeightLigher = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(4)');

    }
}