import { Selector } from 'testcafe';

export default class subscribeConfirm {
    constructor () {
      this.subsConfirm = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > ul > li:nth-child(4) > a > i');
      this.subsHeadline = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li.tab.active > a');
      this.subsHeadlineText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.subsBodyMessage = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(2)');
      this.subsBodyMessageText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.subsFeeling = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(3) > a');
      this.subsFeelingText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.subsFeelingHappy = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(4) > a');
      this.subsFeelingHappyText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.subsFeelingOk = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(5) > a');
      this.subsFeelingOkText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.subsFeelingNotHappy = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(6) > a');
      this.subsFeelingNotHappyText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.subsShareExperience = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > ul > li:nth-child(7) > a');
      this.subsShareExperienceText = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div.row.content > div > .textcomplete');
      this.subsColor = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(2) > div > ul > li:nth-child(35)');
      this.subsFontSize = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div:nth-child(1) > input');
      this.subsTextTransform = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select');
      this.subsTextTransformNone = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select > option:nth-child(1)');
      this.subsTextTransformCapitalize = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select > option:nth-child(2)');
      this.subsTextTransformUppercase = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select > option:nth-child(3)');
      this.subsTextTransformLowercase = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(3) > div.vfl-has-label.col-xs-6.vfl-label-on-input.vfl-select > select > option:nth-child(4)');
      this.subsFontStyle = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(1) > select');
      this.subsFontStyleNormal = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(1)');
      this.subsFontStyleItalique = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(2)');
      this.subsFontStyleOblique = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(1) > select > option:nth-child(3)');
      this.subsFontWeight = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(2) > select');
      this.subsFontWeightNormal = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(1)');
      this.subsFontWeightBold = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(2)');
      this.subsFontWeightBolder = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(3)');
      this.subsFontWeightLighter = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.vue-tabs.preview-tabs.col-xs-6 > div > div > div > div:nth-child(4) > div:nth-child(2) > select > option:nth-child(4)');
      this.subsSmile = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.flex-row.survey-block > div.flex-item-6.mood-block > div > label:nth-child(3)');
      this.subMeh = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.flex-row.survey-block > div.flex-item-6.mood-block > div > label:nth-child(5)');
      this.subsSad = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.flex-row.survey-block > div.flex-item-6.mood-block > div > label:nth-child(7)');
      this.subsFb = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.flex-row.survey-block > div.flex-item-6.share-block > div > ul > li.sharetool.facebook-sharetool');
      this.subsTwitter = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.flex-row.survey-block > div.flex-item-6.share-block > div > ul > li.sharetool.twitter-sharetool');
      this.subsEmail = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.flex-row.survey-block > div.flex-item-6.share-block > div > ul > li.sharetool.email-sharetool');
      this.subsShare = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-main > div.flex-row.survey-block > div.flex-item-6.share-block > div > ul > li.sharetool.show-all-sharetool');
      this.subsArrowCollaps = Selector('#wpbody-content > main > section:nth-child(3) > div > div.tabs-container > div > div > div > div > div > div.preview.col-xs-6 > div:nth-child(1) > div > div > div > div > div.atm-footer > div.collapse-modal');
    }
}